project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Galen Holt"
  repo-url: https://github.com/galenholt/galenholt.github.io
  page-footer:
    left: "Website created by Galen Holt"
    center:
      - text: "Contact"
        href: mailto:g.holt@deakin.edu.au
      - text: "ORCID"
        href: https://orcid.org/0000-0002-7455-9275
      - text: "Profile"
        href: https://experts.deakin.edu.au/43512-galen-holt/about
    right:
      - icon: github
        href: https://github.com/galenholt
        aria-label: GitHub
      - icon: mortarboard-fill
        href: https://scholar.google.com.au/citations?user=f94WBOoAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: linkedin
        href: https://www.linkedin.com/in/galen-holt-265aa290
        aria-label: LinkedIn
      - icon: mastodon
        href: https://fediscience.org/@galen_holt
        aria-label: Mastodon
    background: secondary
  open-graph: true
  navbar:
    backgroud: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - code_demos.qmd
    right:
      - icon: github
        href: https://github.com/galenholt
        aria-label: GitHub
      - icon: mortarboard-fill
        href: https://scholar.google.com.au/citations?user=f94WBOoAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: linkedin
        href: https://www.linkedin.com/in/galen-holt-265aa290
        aria-label: LinkedIn
      - icon: mastodon
        href: https://fediscience.org/@galen_holt
        aria-label: Mastodon


theme:
  light: flatly
  dark: flatly
  # css: styles.css
toc: true

editor: visual

profile:
  group:
    - [singlefile, fullsite]
