project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - "*.qmd"
    - "!R_py_type_passing.qmd"
website:
  title: "Galen"
  navbar:
    backgroud: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - code_demos.qmd

  sidebar:
    - title: "Research"
      style: 'floating'
      background: light
      contents:
        - research.qmd
    
    - title: "Code Demos"
      contents:
        - code_demos.qmd
        - section: "Small how-tos"
          contents:
            - href: small_helpers/smallpieces.qmd
              text: "Bits and pieces"
            - href: setup/rstudio_themes.qmd
              text: "Editing Rstudio themes"
            - href: small_helpers/zip_downloading.qmd
              text: "Download and unpack zips"
        - section: "Plotting"
          contents:
            - href: plotting/tweaks_tricks.qmd
              text: "Saving and themeing plots"
            - href: plotting/hcl_exploration.qmd
              text: "Exploring HCL colorspace"
            - plotting/fonts.qmd
            - href: plotting/faded_colors.qmd
              text: "Faded 2d colour ramps"
            - href: plotting/math_in_ggplot.qmd
              text: "Latex in ggplot with latex2exp"
        - section: "Theory and simulation"
          contents:
            - href: simmodelling/twoDautocorr.qmd
              text: "Generate 2d autocorrelation"
        - section: "R and python"
          contents:
            - href: RpyEnvs/python_setup.qmd
              text: "Python environments with pyenv and poetry"
            - href: RpyEnvs/python_updated_functions.qmd
              text: "Small python bits"
            - href: RpyEnvs/RandPython.qmd
              text: "Using R and python together"
            - href: RpyEnvs/R_py_shared_projects.qmd
              text: "Shared R-py project structure"
            - href: RpyEnvs/py_r_dates.qmd
              text: "Passing complex objects py-R"
        - section: "Setting things up"
          contents:
            - href: RpyEnvs/rig.qmd
              text: "Managing old R versions with rig"
            - href: RpyEnvs/quarto_website_github.qmd
              text: "Getting this website working"
            - href: RpyEnvs/managingprivate.qmd
              text: "Private data for website repo"
        - section: "Building packages"
          contents:
            - href: package/package_creation.qmd
              text: 'First pass at building a package'
            - href: vicwater/vicwater_testing.qmd
        - section: "Data"
          contents:
            - href: data_acquisition/bom_gauges.qmd
              text: "BOM gauge locations with httr2"
            - href: vicwater/vicwater_api_howtocall.qmd
              text: 'Experimenting with API calls for {vicwater}'
              
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

