---
title: "Updating function defs"
format: html
---

As I develop, I often try a function, tweak it, try again, etc. In R, I can just run the function definition to have access, or `source(filewithfunction.R)`. In python, I could tweak the function, but just trying to use them elsewhere (e.g. in a .qmd) wasn't working, even if I re-ran `import filename`. Clearly, there are differences between `import` in python and `source` in R. After poking around a bit, it looks like python caches on first import, and so subsequent ones don't refresh.

What does seem to work is to run `importlib.reload(filename)`. Obviously we wouldn't put that in a script, but when using an interactive session, it's really helpful. Not sure why this requires a whole separate package, but it works. See \[stackoverflow\] (https://stackoverflow.com/questions/684171/how-to-re-import-an-updated-package-while-in-python-interpreter). It appears to be typical to just restart, but that is really prohibitive if the testing involves processing data that took a long time to create.
